FROM daocloud.io/node:10.15

MAINTAINER daizch <790727372@qq.com>

RUN mkdir -p /data/freelog-report-service

WORKDIR /data/freelog-report-service

COPY . /data/freelog-report-service

RUN npm install

ENV NODE_ENV prod
ENV EGG_SERVER_ENV prod
ENV PORT 5113

EXPOSE 5113

CMD [ "npm", "start" ]